import type { JsonSchema, ToolDef } from './types.ts'

/**
 * Инструменты Blender через мост blender-ai-mcp.
 *
 * ФАЙЛ СГЕНЕРИРОВАН из ответа самого сервера — схемы не написаны руками, и это
 * принципиально. Придуманная по документации схема gh_apply_graph стоила дня:
 * модель вызывала инструмент, плагин отвечал, что аргументы не те, а выглядело
 * это как «модель игнорирует Grasshopper». Здесь контракт взят у источника.
 *
 * Отобрано 37 инструментов из 187. Остальные не выброшены, а не
 * опубликованы: их описания оплачивались бы на каждом круге, а нужны редко.
 * Перегенерировать: node scripts/gen-blender-tools.mjs
 */
export const BLENDER_AI_TOOLS: ToolDef[] = [
  {
    name: 'bl_scene_context',
    engine: 'blender',
    command: 'bl:scene_context',
    description: "[SCENE][READ-ONLY][SAFE] Quick context queries for scene state. Actions: - \"mode\": Returns current Blender mode, active object, selection count. - \"selection\": Returns selected objects list + edit mode vertex/edge/face counts. Workflow: READ-ONLY | FIRST STEP → check context before any operation Examples: scene_context(action=\"mode\") scene_context(action=\"selection\")",
    parameters: {"additionalProperties":false,"properties":{"action":{"enum":["mode","selection"],"type":"string"}},"required":["action"],"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_scene_list_objects',
    engine: 'blender',
    command: 'bl:scene_list_objects',
    description: "[SCENE][SAFE][READ-ONLY] Lists all objects in the current Blender scene with their types. Workflow: READ-ONLY | START → understand scene",
    parameters: {"additionalProperties":false,"properties":{},"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_scene_clean_scene',
    engine: 'blender',
    command: 'bl:scene_clean_scene',
    description: "[SCENE][DESTRUCTIVE] Deletes objects from the scene. WARNING: If keep_lights_and_cameras=False, deletes EVERYTHING (hard reset). Workflow: START → fresh scene | AFTER → modeling_create_primitive",
    parameters: {"additionalProperties":false,"properties":{"keep_lights_and_cameras":{"anyOf":[{"type":"boolean"},{"type":"null"}],"default":null,"description":"Canonical public cleanup flag. If True (default),\nkeeps Lights and Cameras. If False, deletes EVERYTHING (hard reset)."},"keep_lights":{"anyOf":[{"type":"boolean"},{"type":"null"}],"default":null,"description":"Legacy compatibility-only split flag. Use only when it\nmatches `keep_cameras`."},"keep_cameras":{"anyOf":[{"type":"boolean"},{"type":"null"}],"default":null,"description":"Legacy compatibility-only split flag. Use only when it\nmatches `keep_lights`."}},"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_scene_delete_object',
    engine: 'blender',
    command: 'bl:scene_delete_object',
    description: "[SCENE][DESTRUCTIVE] Deletes an object from the scene by name. This permanently removes the object. Workflow: DESTRUCTIVE | BEFORE → scene_list_objects",
    parameters: {"additionalProperties":false,"properties":{"name":{"type":"string","description":"Name of the object to delete."}},"required":["name"],"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_scene_rename_object',
    engine: 'blender',
    command: 'bl:scene_rename_object',
    description: "[OBJECT MODE][SCENE][SAFE] Renames an object in the scene. Workflow: AFTER → scene_list_objects | USE FOR → organizing imported models",
    parameters: {"additionalProperties":false,"properties":{"old_name":{"type":"string","description":"Current name of the object"},"new_name":{"type":"string","description":"New name for the object"}},"required":["old_name","new_name"],"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_scene_get_bounding_box',
    engine: 'blender',
    command: 'bl:scene_get_bounding_box',
    description: "[OBJECT MODE][SAFE][READ-ONLY] Gets bounding box corners for an object. Workflow: READ-ONLY | USE FOR → spatial analysis, collision detection planning Returns all 8 corners of the axis-aligned bounding box plus center and dimensions.",
    parameters: {"additionalProperties":false,"properties":{"object_name":{"type":"string","description":"Name of the object to query"},"world_space":{"default":true,"type":"boolean","description":"If True, returns world coordinates. If False, local coordinates."},"assistant_summary":{"default":false,"type":"boolean","description":"If True, attaches a bounded assistant summary for the bounding-box payload."}},"required":["object_name"],"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_scene_get_viewport',
    engine: 'blender',
    command: 'bl:scene_get_viewport',
    description: "Get a visual preview of the scene (OpenGL Viewport Render). Workflow: LAST STEP → visual verification | USE → AI preview The tool can return the viewport in multiple formats, controlled by ``output_mode``: * ``IMAGE`` (default): Returns a FastMCP ``Image`` resource (best for clients that natively support image resources, like Cline). * ``BASE64``: Returns the raw base64-encoded JPEG data as a string for direct consum",
    parameters: {"additionalProperties":false,"properties":{"width":{"default":1024,"type":"integer","description":"Image width in pixels."},"height":{"default":768,"type":"integer","description":"Image height in pixels."},"shading":{"default":"SOLID","type":"string","description":"Viewport shading mode ('WIREFRAME', 'SOLID', 'MATERIAL', 'RENDERED')."},"camera_name":{"default":null,"type":"string","description":"Name of the camera to use. If None or \"USER_PERSPECTIVE\", uses a temporary\ncamera."},"focus_target":{"default":null,"type":"string","description":"Name of the object to focus on. Only works if camera_name is\nNone/\"USER_PERSPECTIVE\"."},"view_name":{"default":null,"type":"string","description":"Optional standard user-view preset ('FRONT', 'RIGHT', 'TOP') applied\nbefore capture when using USER_PERSPECTIVE."},"orbit_horizontal":{"default":0,"type":"number","description":"Optional horizontal orbit in degrees applied to USER_PERSPECTIVE before capture."},"orbit_vertical":{"default":0,"type":"number","description":"Optional vertical orbit in degrees applied to USER_PERSPECTIVE before capture."},"zoom_factor":{"default":null,"type":"number","description":"Optional user-view zoom factor applied with focus_target or current USER_PERSPECTIVE view."},"persist_view":{"default":false,"type":"boolean","description":"If True, keeps the adjusted USER_PERSPECTIVE after capture. Defaults to False."},"output_mode":{"default":"IMAGE","enum":["IMAGE","BASE64","FILE","MARKDOWN"],"type":"string","description":"Output format selector: \"IMAGE\", \"BASE64\", \"FILE\", or \"MARKDOWN\"."}},"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_scene_measure_dimensions',
    engine: 'blender',
    command: 'bl:scene_measure_dimensions',
    description: "[OBJECT MODE][SAFE][READ-ONLY] Measures object dimensions from its bounding box. Workflow: READ-ONLY | USE FOR → proportions, scaling checks, truth-layer verification",
    parameters: {"additionalProperties":false,"properties":{"object_name":{"type":"string","description":"Object to measure"},"world_space":{"default":true,"type":"boolean","description":"If True, measures transformed world dimensions. If False, measures local dimensions."}},"required":["object_name"],"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_scene_measure_gap',
    engine: 'blender',
    command: 'bl:scene_measure_gap',
    description: "[OBJECT MODE][SAFE][READ-ONLY] Measures the nearest gap/contact state between two objects. Workflow: READ-ONLY | USE FOR → clearance, contact, and fit verification Uses the current truth path for the pair. For mesh pairs the handler prefers a bounded mesh-surface relation and also reports bbox fallback diagnostics such as `bbox_relation`; otherwise it falls back to bbox-only semantics. `gap=0` still means the measure",
    parameters: {"additionalProperties":false,"properties":{"from_object":{"type":"string","description":"Source object name"},"to_object":{"type":"string","description":"Target object name"},"tolerance":{"default":0.0001,"type":"number","description":"Contact threshold in Blender units"}},"required":["from_object","to_object"],"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_scene_assert_dimensions',
    engine: 'blender',
    command: 'bl:scene_assert_dimensions',
    description: "[OBJECT MODE][SAFE][READ-ONLY] Asserts that object dimensions match an expected vector. Workflow: READ-ONLY | USE FOR → explicit size verification without outer-LLM arithmetic",
    parameters: {"additionalProperties":false,"properties":{"object_name":{"type":"string","description":"Object to verify"},"expected_dimensions":{"anyOf":[{"type":"string"},{"items":{"type":"number"},"type":"array"}],"description":"Expected [x, y, z] dimensions as a list or string"},"tolerance":{"default":0.0001,"type":"number","description":"Allowed per-axis difference in Blender units"},"world_space":{"default":true,"type":"boolean","description":"If True, compares world dimensions. If False, compares local dimensions."}},"required":["object_name","expected_dimensions"],"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_scene_assert_contact',
    engine: 'blender',
    command: 'bl:scene_assert_contact',
    description: "[OBJECT MODE][SAFE][READ-ONLY] Asserts that two objects satisfy the expected contact relation. Workflow: READ-ONLY | USE FOR → deterministic fit/contact postconditions Objects pass when the measured gap from the current truth path is within `max_gap`, and overlap is rejected unless `allow_overlap=True`. For mesh pairs this now prefers mesh-surface contact semantics instead of bbox touching alone, while still exposing",
    parameters: {"additionalProperties":false,"properties":{"from_object":{"type":"string","description":"Source object name"},"to_object":{"type":"string","description":"Target object name"},"max_gap":{"default":0.0001,"type":"number","description":"Maximum allowed separation in Blender units"},"allow_overlap":{"default":false,"type":"boolean","description":"If True, overlap is accepted as a passing relation"}},"required":["from_object","to_object"],"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_modeling_create_primitive',
    engine: 'blender',
    command: 'bl:modeling_create_primitive',
    description: "[OBJECT MODE][SAFE][NON-DESTRUCTIVE] Creates a 3D primitive object. Workflow: START → new object | AFTER → modeling_transform, scene_set_mode('EDIT') Public guided usage: create the primitive with its base shape first, then call `modeling_transform_object(scale=...)` for non-uniform scale.",
    parameters: {"additionalProperties":false,"properties":{"primitive_type":{"type":"string","description":"\"Cube\", \"Sphere\", \"Cylinder\", \"Plane\", \"Cone\", \"Monkey\", \"Torus\"."},"radius":{"default":1,"type":"number","description":"Radius for Sphere/Cylinder/Cone."},"size":{"default":2,"type":"number","description":"Size for Cube/Plane/Monkey."},"location":{"anyOf":[{"type":"string"},{"items":{"type":"number"},"type":"array"}],"default":[0,0,0],"description":"[x, y, z] coordinates. Can be a list [0.0, 0.0, 0.0] or string '[0.0, 0.0, 0.0]'."},"rotation":{"anyOf":[{"type":"string"},{"items":{"type":"number"},"type":"array"}],"default":[0,0,0],"description":"[rx, ry, rz] rotation in radians. Can be a list or string."},"name":{"default":null,"type":"string","description":"Optional name for the new object."},"scale":{"anyOf":[{"type":"string"},{"items":{"type":"number"},"type":"array"},{"type":"null"}],"default":null},"segments":{"anyOf":[{"type":"integer"},{"type":"null"}],"default":null},"rings":{"anyOf":[{"type":"integer"},{"type":"null"}],"default":null},"subdivisions":{"anyOf":[{"type":"integer"},{"type":"null"}],"default":null},"collection_name":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null},"guided_role":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null},"role_group":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null}},"required":["primitive_type"],"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_modeling_transform_object',
    engine: 'blender',
    command: 'bl:modeling_transform_object',
    description: "[OBJECT MODE][SAFE][NON-DESTRUCTIVE] Transforms (move, rotate, scale) an existing object. Workflow: AFTER → modeling_create_primitive | BEFORE → scene_set_mode('EDIT')",
    parameters: {"additionalProperties":false,"properties":{"name":{"type":"string","description":"Name of the object."},"location":{"anyOf":[{"type":"string"},{"items":{"type":"number"},"type":"array"},{"type":"null"}],"default":null,"description":"New [x, y, z] coordinates (optional). Can be a list [0.0, 0.0, 2.0] or string '[0.0, 0.0, 2.0]'."},"rotation":{"anyOf":[{"type":"string"},{"items":{"type":"number"},"type":"array"},{"type":"null"}],"default":null,"description":"New [rx, ry, rz] rotation in radians (optional). Can be a list or string."},"scale":{"anyOf":[{"type":"string"},{"items":{"type":"number"},"type":"array"},{"type":"null"}],"default":null,"description":"New [sx, sy, sz] scale factors (optional). Can be a list or string."},"guided_role":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null},"role_group":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null}},"required":["name"],"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_modeling_add_modifier',
    engine: 'blender',
    command: 'bl:modeling_add_modifier',
    description: "[OBJECT MODE][SAFE][NON-DESTRUCTIVE] Adds a modifier to an object. Use this object-level modifier tool when you want a controlled non-destructive stack change. Workflow: NON-DESTRUCTIVE | AFTER → modeling_apply_modifier",
    parameters: {"additionalProperties":false,"properties":{"name":{"type":"string","description":"Object name."},"modifier_type":{"type":"string","description":"Type of modifier (e.g., 'SUBSURF', 'BEVEL', 'MIRROR', 'BOOLEAN')."},"properties":{"anyOf":[{"type":"string"},{"additionalProperties":true,"type":"object"},{"type":"null"}],"default":null,"description":"Dictionary of modifier properties to set (e.g., {'levels': 2}). Can be a dict or string '{\"levels\": 2}'.\nBOOLEAN note: to set the cutter/target object, pass `{\"object\": \"<ObjectName>\"}` (or alias `object_name`)\nwhere the value is the name of an existing Blender object."}},"required":["name","modifier_type"],"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_modeling_apply_modifier',
    engine: 'blender',
    command: 'bl:modeling_apply_modifier',
    description: "[OBJECT MODE][DESTRUCTIVE] Applies a modifier, making its changes permanent to the mesh. Workflow: BEFORE → modeling_list_modifiers | DESTRUCTIVE - bakes changes",
    parameters: {"additionalProperties":false,"properties":{"name":{"type":"string","description":"Object name."},"modifier_name":{"type":"string","description":"The name of the modifier to apply."}},"required":["name","modifier_name"],"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_modeling_join_objects',
    engine: 'blender',
    command: 'bl:modeling_join_objects',
    description: "[OBJECT MODE][DESTRUCTIVE] Joins multiple mesh objects into a single mesh. IMPORTANT: The LAST object in the list becomes the Active Object (Base). Workflow: BEFORE → mesh_boolean workflow | AFTER → mesh_select_linked",
    parameters: {"additionalProperties":false,"properties":{"object_names":{"items":{"type":"string"},"type":"array","description":"A list of names of the objects to join."}},"required":["object_names"],"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_modeling_set_origin',
    engine: 'blender',
    command: 'bl:modeling_set_origin',
    description: "[OBJECT MODE][DESTRUCTIVE] Sets the origin point of an object. Workflow: AFTER → geometry changes | BEFORE → modeling_transform",
    parameters: {"additionalProperties":false,"properties":{"name":{"type":"string","description":"Object name."},"type":{"type":"string","description":"Origin type (e.g., 'ORIGIN_GEOMETRY', 'ORIGIN_CURSOR', 'ORIGIN_CENTER_OF_MASS')."}},"required":["name","type"],"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_mesh_boolean',
    engine: 'blender',
    command: 'bl:mesh_boolean',
    description: "[EDIT MODE][SELECTION-BASED][DESTRUCTIVE] Boolean operation on selected geometry. Formula: Unselected - Selected (for DIFFERENCE). TIP: For object-level booleans, prefer 'modeling_add_modifier(BOOLEAN)' (safer). Workflow: BEFORE → modeling_join_objects + mesh_select_linked | AFTER → mesh_merge_by_distance, mesh_fill_holes",
    parameters: {"additionalProperties":false,"properties":{"operation":{"default":"DIFFERENCE","type":"string","description":"'INTERSECT', 'UNION', 'DIFFERENCE'."},"solver":{"default":"EXACT","type":"string","description":"'EXACT' (modern, recommended) or 'FLOAT' (legacy)."}},"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_mesh_extrude_region',
    engine: 'blender',
    command: 'bl:mesh_extrude_region',
    description: "[EDIT MODE][SELECTION-BASED][DESTRUCTIVE] Extrudes selected geometry. WARNING: If 'move' is None, new geometry is created in-place (overlapping). Always provide 'move' vector or follow up with transform. Workflow: BEFORE → mesh_select_* | AFTER → mesh_smooth, mesh_merge_by_distance",
    parameters: {"additionalProperties":false,"properties":{"move":{"anyOf":[{"type":"string"},{"items":{"type":"number"},"type":"array"},{"type":"null"}],"default":null,"description":"Optional [x, y, z] vector to move extruded region. Can be a list or string '[0.0, 0.0, 2.0]'."}},"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_mesh_bevel',
    engine: 'blender',
    command: 'bl:mesh_bevel',
    description: "[EDIT MODE][SELECTION-BASED][DESTRUCTIVE] Bevels selected edges or vertices. Workflow: BEFORE → mesh_select_loop, mesh_select_ring | AFTER → mesh_smooth",
    parameters: {"additionalProperties":false,"properties":{"offset":{"default":0.1,"type":"number","description":"Size of the bevel (distance/width)."},"segments":{"default":1,"type":"integer","description":"Number of segments (rounding)."},"profile":{"default":0.5,"type":"number","description":"Shape of the bevel (0.5 is round)."},"affect":{"default":"EDGES","type":"string","description":"'EDGES' or 'VERTICES'."}},"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_mesh_inset',
    engine: 'blender',
    command: 'bl:mesh_inset',
    description: "[EDIT MODE][SELECTION-BASED][DESTRUCTIVE] Insets selected faces (creates smaller faces inside). Workflow: BEFORE → mesh_select_*(FACE) | AFTER → mesh_extrude_region",
    parameters: {"additionalProperties":false,"properties":{"thickness":{"default":0,"type":"number","description":"Amount to inset."},"depth":{"default":0,"type":"number","description":"Amount to move the inset face in/out."}},"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_mesh_loop_cut',
    engine: 'blender',
    command: 'bl:mesh_loop_cut',
    description: "[EDIT MODE][SELECTION-BASED][DESTRUCTIVE] Adds cuts to mesh geometry. IMPORTANT: Uses 'subdivide' on SELECTED edges. Select edges perpendicular to desired cut direction first. Workflow: BEFORE → mesh_select_by_index(EDGE) | AFTER → mesh_select_loop",
    parameters: {"additionalProperties":false,"properties":{"number_cuts":{"default":1,"type":"integer","description":"Number of cuts to make."},"smoothness":{"default":0,"type":"number","description":"Smoothness of the subdivision."}},"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_mesh_subdivide',
    engine: 'blender',
    command: 'bl:mesh_subdivide',
    description: "[EDIT MODE][SELECTION-BASED][DESTRUCTIVE] Subdivides selected geometry. Workflow: BEFORE → mesh_select_* | AFTER → mesh_smooth",
    parameters: {"additionalProperties":false,"properties":{"number_cuts":{"default":1,"type":"integer","description":"Number of cuts."},"smoothness":{"default":0,"type":"number","description":"Smoothness factor (0.0 to 1.0)."}},"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_mesh_smooth',
    engine: 'blender',
    command: 'bl:mesh_smooth',
    description: "[EDIT MODE][SELECTION-BASED][NON-DESTRUCTIVE] Smooths selected vertices. Uses Laplacian smoothing to refine organic shapes and remove hard edges. Workflow: BEFORE → mesh_boolean, mesh_extrude, mesh_bevel | LAST STEP in edit workflow",
    parameters: {"additionalProperties":false,"properties":{"iterations":{"default":1,"type":"integer","description":"Number of smoothing passes (1-100). More = smoother"},"factor":{"default":0.5,"type":"number","description":"Smoothing strength (0.0-1.0). 0=no effect, 1=maximum smoothing"}},"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_mesh_mirror',
    engine: 'blender',
    command: 'bl:mesh_mirror',
    description: "[EDIT MODE][SELECTION-BASED][DESTRUCTIVE] Mirrors selected geometry. Unlike symmetrize (which replaces one side), mirror creates a copy. Useful for: - Duplicating symmetric parts - Creating mirrored elements For non-destructive mirroring, use modeling_add_modifier(type=\"MIRROR\"). Workflow: BEFORE → mesh_select geometry to mirror",
    parameters: {"additionalProperties":false,"properties":{"axis":{"default":"X","enum":["X","Y","Z"],"type":"string","description":"Axis to mirror across (X, Y, or Z)."},"use_mirror_merge":{"default":true,"type":"boolean","description":"Merge vertices at mirror plane."},"merge_threshold":{"default":0.001,"type":"number","description":"Distance for merging mirrored vertices."}},"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_mesh_spin',
    engine: 'blender',
    command: 'bl:mesh_spin',
    description: "[EDIT MODE][SELECTION-BASED][DESTRUCTIVE] Spins/lathes selected geometry around an axis. Creates rotational geometry like vases, bowls, or circular patterns. Workflow: BEFORE → mesh_select_* (select profile) | AFTER → mesh_merge_by_distance",
    parameters: {"additionalProperties":false,"properties":{"steps":{"default":12,"type":"integer","description":"Number of steps/segments for the spin (12 = 30° per step for full circle)."},"angle":{"default":6.283185,"type":"number","description":"Total angle in radians (default 6.283185 = 360° = full circle).\nCommon values: 3.14159 (180°), 1.5708 (90°)"},"axis":{"default":"Z","enum":["X","Y","Z"],"type":"string","description":"Axis to spin around (X, Y, or Z)."},"center":{"anyOf":[{"items":{"type":"number"},"type":"array"},{"type":"null"}],"default":null,"description":"Optional [x, y, z] center point for spin. Default is 3D cursor."},"dupli":{"default":false,"type":"boolean","description":"If True, duplicates geometry instead of extruding."}},"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_mesh_select',
    engine: 'blender',
    command: 'bl:mesh_select',
    description: "[EDIT MODE][SELECTION-BASED][SAFE] Simple selection operations for mesh geometry. Actions: - \"all\": Selects all geometry. No params required. - \"none\": Deselects all geometry. No params required. - \"linked\": Selects all geometry connected to current selection. - \"more\": Grows selection by 1 step. - \"less\": Shrinks selection by 1 step. - \"boundary\": Selects boundary edges/vertices. Optional: boundary_mode (EDGE/VERT).",
    parameters: {"additionalProperties":false,"properties":{"action":{"enum":["all","none","linked","more","less","boundary"],"type":"string"},"boundary_mode":{"default":"EDGE","enum":["EDGE","VERT"],"type":"string"}},"required":["action"],"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_curve_create',
    engine: 'blender',
    command: 'bl:curve_create',
    description: "[OBJECT MODE][SAFE] Creates a curve primitive object. Curves are non-destructive and can be converted to mesh via curve_to_mesh. Workflow: START → curve_to_mesh (if mesh needed) | USE FOR → paths, profiles, modeling guides",
    parameters: {"additionalProperties":false,"properties":{"curve_type":{"default":"BEZIER","enum":["BEZIER","NURBS","PATH","CIRCLE"],"type":"string","description":"Type of curve to create.\n- BEZIER: Bezier curve with control handles (default)\n- NURBS: NURBS curve for smooth surfaces\n- PATH: NURBS path for animation/follow paths\n- CIRCLE: Bezier circle (closed curve)"},"location":{"anyOf":[{"items":{"type":"number"},"type":"array"},{"type":"null"}],"default":null,"description":"Optional [x, y, z] position. Default is [0, 0, 0]."}},"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_curve_to_mesh',
    engine: 'blender',
    command: 'bl:curve_to_mesh',
    description: "[OBJECT MODE][DESTRUCTIVE] Converts a curve object to mesh geometry. The curve is permanently converted - use modeling_add_modifier for non-destructive workflow. Workflow: BEFORE → curve_create | AFTER → mesh_* operations",
    parameters: {"additionalProperties":false,"properties":{"object_name":{"type":"string","description":"Name of the curve object to convert."}},"required":["object_name"],"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_material_create',
    engine: 'blender',
    command: 'bl:material_create',
    description: "[OBJECT MODE][SAFE] Creates a new PBR material with Principled BSDF. Workflow: AFTER → material_assign",
    parameters: {"additionalProperties":false,"properties":{"name":{"type":"string","description":"Material name"},"base_color":{"anyOf":[{"type":"string"},{"items":{"type":"number"},"type":"array"},{"type":"null"}],"default":null,"description":"RGBA color [0-1] (default: [0.8, 0.8, 0.8, 1.0]). Accepts list or string \"[r,g,b,a]\"."},"metallic":{"default":0,"type":"number","description":"Metallic value 0-1"},"roughness":{"default":0.5,"type":"number","description":"Roughness value 0-1"},"emission_color":{"anyOf":[{"type":"string"},{"items":{"type":"number"},"type":"array"},{"type":"null"}],"default":null,"description":"Emission RGB [0-1]. Accepts list or string \"[r,g,b]\"."},"emission_strength":{"default":0,"type":"number","description":"Emission strength"},"alpha":{"default":1,"type":"number","description":"Alpha/opacity 0-1"}},"required":["name"],"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_material_assign',
    engine: 'blender',
    command: 'bl:material_assign',
    description: "[OBJECT MODE/EDIT MODE][SELECTION-BASED] Assigns material to object or selected faces. In Object Mode: Assigns material to entire object In Edit Mode with assign_to_selection=True: Assigns to selected faces only Workflow: BEFORE → material_create, mesh_select",
    parameters: {"additionalProperties":false,"properties":{"material_name":{"type":"string","description":"Name of existing material"},"object_name":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"description":"Target object (default: active object)"},"slot_index":{"anyOf":[{"type":"integer"},{"type":"null"}],"default":null,"description":"Material slot index (default: auto)"},"assign_to_selection":{"default":false,"type":"boolean","description":"If True and in Edit Mode, assign to selected faces"}},"required":["material_name"],"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_extraction_render_angles',
    engine: 'blender',
    command: 'bl:extraction_render_angles',
    description: "[OBJECT MODE][SAFE] Renders object from multiple angles for LLM Vision analysis. Workflow: AFTER → component analysis | USE FOR → LLM Vision semantic extraction Renders the object from predefined angles: - front: Y- direction - back: Y+ direction - left: X- direction - right: X+ direction - top: Z+ direction (looking down) - iso: Isometric view (45° from front-right-top)",
    parameters: {"additionalProperties":false,"properties":{"object_name":{"type":"string","description":"Object to render (others will be hidden)"},"angles":{"anyOf":[{"items":{"type":"string"},"type":"array"},{"type":"null"}],"default":null,"description":"List of angles to render (default: all 6)"},"resolution":{"default":512,"type":"integer","description":"Image resolution in pixels (default 512)"},"output_dir":{"default":"/tmp/extraction_renders","type":"string","description":"Directory to save renders"}},"required":["object_name"],"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_system_save_file',
    engine: 'blender',
    command: 'bl:system_save_file',
    description: "[SCENE][DESTRUCTIVE] Saves the current Blender file. If no filepath is provided: - Saves to current file path if file was previously saved - Creates auto-save in temp directory if file is unsaved WARNING: Overwrites existing file at filepath! Workflow: CHECKPOINT -> save progress | BEFORE -> risky operations",
    parameters: {"additionalProperties":false,"properties":{"filepath":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"description":"Path to save (default: current file path, or temp if unsaved)"},"compress":{"default":true,"type":"boolean","description":"Compress .blend file (default: True)"}},"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_system_new_file',
    engine: 'blender',
    command: 'bl:system_new_file',
    description: "[SCENE][DESTRUCTIVE] Creates a new Blender file (clears current scene). WARNING: Unsaved changes will be lost! Use system_save_file first if needed. Workflow: START FRESH -> new project | AFTER -> system_save_file",
    parameters: {"additionalProperties":false,"properties":{"load_ui":{"default":false,"type":"boolean","description":"Load UI layout from startup file (default: False)"}},"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_system_undo',
    engine: 'blender',
    command: 'bl:system_undo',
    description: "[SCENE][NON-DESTRUCTIVE] Undoes the last operation(s). Safe way to revert changes during AI-assisted modeling sessions. Limited to 10 steps per call for safety. Workflow: ERROR RECOVERY -> undo mistakes | AFTER -> any destructive operation",
    parameters: {"additionalProperties":false,"properties":{"steps":{"default":1,"type":"integer","description":"Number of steps to undo (default: 1, max: 10)"}},"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_export_glb',
    engine: 'blender',
    command: 'bl:export_glb',
    description: "[OBJECT MODE][SCENE][SAFE] Exports scene or selected objects to GLB/GLTF format. GLB is the binary variant of GLTF - ideal for web, game engines (Unity, Unreal, Godot). Supports PBR materials, animations, and skeletal rigs. Workflow: BEFORE -> scene_list_objects (verify objects) | AFTER -> file ready for import",
    parameters: {"additionalProperties":false,"properties":{"filepath":{"type":"string","description":"Output file path (must end with .glb or .gltf)"},"export_selected":{"default":false,"type":"boolean","description":"Export only selected objects (default: entire scene)"},"export_animations":{"default":true,"type":"boolean","description":"Include animations"},"export_materials":{"default":true,"type":"boolean","description":"Include materials and textures"},"apply_modifiers":{"default":true,"type":"boolean","description":"Apply modifiers before export"}},"required":["filepath"],"type":"object"} as unknown as JsonSchema,
  },
  {
    name: 'bl_export_obj',
    engine: 'blender',
    command: 'bl:export_obj',
    description: "[OBJECT MODE][SCENE][SAFE] Exports scene or selected objects to OBJ format. OBJ is a simple, universal mesh format supported by virtually all 3D software. Creates .obj (geometry) and optionally .mtl (materials) files. Workflow: BEFORE -> scene_list_objects (verify objects) | AFTER -> file ready for import",
    parameters: {"additionalProperties":false,"properties":{"filepath":{"type":"string","description":"Output file path (must end with .obj)"},"export_selected":{"default":false,"type":"boolean","description":"Export only selected objects"},"apply_modifiers":{"default":true,"type":"boolean","description":"Apply modifiers before export"},"export_materials":{"default":true,"type":"boolean","description":"Export .mtl material file"},"export_uvs":{"default":true,"type":"boolean","description":"Include UV coordinates"},"export_normals":{"default":true,"type":"boolean","description":"Include vertex normals"},"triangulate":{"default":false,"type":"boolean","description":"Convert quads/ngons to triangles"}},"required":["filepath"],"type":"object"} as unknown as JsonSchema,
  },
]
